### ISSUE TITLE
`SubtypeOfX` that uses `is_number/1`

### ISSUE THREAD

**Issue by aDaichiOta** [skirino/croma#11]
Currently `SubtypeOfFloat` exists, but `SubtypeOfNumber` does not. `SubtypeOfFloat` validates values using `is_float/1`, so `0` is not valid.
By the way, there are no integers in JavaScript. `JSON.stringify({val: 0.0})` becomes `{"val": 0}`. That is, `SubtypeOfFloat` doesn't accept `0`.
Could you add a `SubtypeOfNumber` that uses `is_number/1` or change `SubtypeOfFloat` to use `is_number/1` instead of `is_float/1`?

**Comment by skirino** [comment]
Thanks for filing this issue. Added `SubtypeOfNumber` and it's included in 0.11.1 release.

**Comment by aDaichiOta** [comment]
Thank you. I will use it later.
