### ISSUE TITLE
Croma.Struct should accept non Croma types as well

### ISSUE THREAD

**Issue by seivan** [skirino/croma#8]
It would be nice if it could be used with types that don't necessarily have `guard/valid` functions. 
I got something similar here https://gist.github.com/seivan/5cf3a6e6234d429ac227440607c9e452 and the benefit is that it would work with third party types.

**Comment by skirino** [comment]
`Croma.Struct` accepts arbitrary [type modules](https://github.com/skirino/croma#type-modules) for its fields.
I'm not sure what you are suggesting here; what is the problem of the current version of `Croma.Struct`?

If what you want is a variant of `Croma.Struct` that simply generates
- `defstruct unquote(Keyword.keys(fields))` and
- `@type t :: %__MODULE__{unquote_splicing(fields)}`,

then go with your `TypedStruct` (or something like that).
Croma's type module mechanism is designed for rigorous runtime validation, and for this purpose `Croma.Struct` requires each field to have its corresponding `valid?/1` function.

**Comment by seivan** [comment]
I'm referring to the docs: https://hexdocs.pm/croma/Croma.Struct.html#content

```elixir
required: @type t
required: @spec valid?(term) :: boolean
```

It was unclear if this applies to all fields or just those using the module name instead of type.

**Comment by skirino** [comment]
You cannot specify types (e.g. `String.t`) for `:fields` option of `use Croma.Struct`; only type modules are allowed.
As a documentation issue, I've tried to clarify that **all** fields must have corresponding type modules in the docs.
https://github.com/skirino/croma/commit/d8d20abd9f014a30f267ada719b6b41d44fa5ddd
I'm closing this but feel free to reopen if you have further questions/issues.
