### ISSUE TITLE
Croma is missing some of the newer elixir types.

### ISSUE THREAD

**Issue by yuchunc** [skirino/croma#9]
Hi @skirino ,

I am a new member with ATL, while doing reviews for our interns, we released Croma is missing some of the newer elixir types. Such as, Date.

Looking in to the code base, I found `BuiltinType` encapsulates most of the basic Elixir types. I propose a few changes:

1. Instead of using guard clause in `validat?`, use a simple conditional. These would allow a broad set of newer validation function to work, like `valid_date`.
2. Include the newer types. (ie. Calendar, Date, Datetime, NaiveDatetime, Regex... etc)

I would also propose to run `mix format` to align the project with the new community standard.

Please let me know how you like to proceed, I can help with the respective changes.

**Comment by skirino** [comment]
Hi @yuchunc,

- I have no idea on what you mean in (1); could you elaborate more on what you want to achieve?
- Regarding (2):
The definition of the word "builtin" in `Croma.BuiltinType` module is that it's built in the runtime (ErlangVM), not in the Elixir stdlib. The types above are all structs and defined in the Elixir stdlib; they are thus out of scope of `Croma.BuiltinType` module. Again I'm not sure what is the use case. What kind of code do you want to write with croma?

---

About some unimportant points you mentioned:
- Please be explicit about what "ATL" refers to.
- I'm personally not satisfied with code format results of `mix format`.
I prefer code style that encourages to define many small functions and that leverages vertical alignments. Code modification cost isn't a big deal; code reading cost is.
Code formatter is useful for projects with multiple developers for consistency's sake, but `croma` is primarily a personal project (though contributions are more than welcomed, of course!).
So I currently have no plan to use `mix format`.

**Comment by yuchunc** [comment]
Pardon me for being vague, ATL = Access Taiwan Lab.

> I have no idea on what you mean in (1); could you elaborate more on what you want to achieve?

Consider https://github.com/skirino/croma/blob/master/lib/croma/builtin_type.ex#L47-L50. At this moment, `valid?/1` is evaluating in guard clause, it is limiting the validate function that can be use. If it's changed to a conditional clause (if..else, case, ... etc), it will be able to utilize more validating function, without the need for macro.

> Regarding (2): ...

Understand. We are trying to use `v[Date.t]` when using `defun/2`. We figure out the work around to wrap `Date` type in a local type, and validate it there. We settle on something like this: 

```elixir
defun some_date_fn(date :: v[Project.Date.t]) :: result do
...
end
```

> I'm personally not satisfied with code format results of mix format. ....

Gotcha, while I also don't agree with everything from the formatter, it does saves much of the back and forth in team situations. 

Thank you for clarifying the design decision, since we resolved our issue, I am going to go a head and close this issue.

**Comment by skirino** [comment]
@yuchunc 
Thank you for the clarification.
Just FYI:

> Consider https://github.com/skirino/croma/blob/master/lib/croma/builtin_type.ex#L47-L50 ...

It's just an implementation detail; I'm still not sure why you care about it.
Actually we don't have to use guard here and we should be able to simply use `unquote(guard_expr)`.

> We are trying to use v[Date.t] when using defun/2...

To validate whether a parameter is a struct which is defined in the stdlib, simple patten matching (i.e. checking only `:__struct__` field) like the following should be OK most of the time.
```ex
defun some_date_fn(date = %Date{} :: Date.t) :: result do
  ...
end
```

**Comment by yuchunc** [comment]
> It's just an implementation detail; I'm still not sure why you care about it.

Using a simple case statement, or what you done in the latest commit, can allow validation statement outside of guard's limited set of functions. My original request, before your clarification, was for adding Date.t validat, and it wouldn't work inside a guard without sprinkling in a bit of macros.

>To validate whether a parameter is a struct which is defined in the stdlib, ...

That is a good point, I'll share it with the team.

Thank you
